### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by shayegh** [simoneldevig/jira-toggl#10]
Hi, 
Times are loaded successfully from toggle and I'm logged in my Jira server, but when I click the "Log work" button I got a network error. and nothing is logged.

**Comment by simoneldevig** [comment]
Hi,

It sounds like the call to JIRA fails. Did you check that JIRA url and email are correct? 

Maybe it's related to some kind of JIRA Server auth that differes from JIRA Cloud?

**Comment by shayegh** [comment]
I found that the time format that my server accepts is like '2020-09-03T15:26:55.000+0430' but your format is different. may you help me?

**Comment by simoneldevig** [comment]
Unfortunately not since I don't have access to a Jira server to test with. But you are welcome to add an option to change the date format in the settings page. Just create a pull request and I'll have a look at it 👍

**Comment by simoneldevig** [comment]
Solved in #
