### ISSUE TITLE
error 403 

### ISSUE THREAD

**Issue by herrpina** [simoneldevig/jira-toggl#16]
Hi,

I’m trying to use this add on and I get error 403 on Firefox Mac and PC. API token and username, jira server are correct. 
I get the listing of my projects, ready to import but whenever I press the sync to jira-button, I receive Error 403. So the add on can make the toggl connection but writing into the jira ticket doesn’t work...

**Comment by simoneldevig** [comment]
@herrpina are you logged into JIRA in another tab? 

To make sure that you're authenticated to use the JIRA api's you can try to call https://your-domain.atlassian.com/rest/api/3/dashboard in a new tab to see if you get any data.

Have you tried to test in Chrome?

**Comment by herrpina** [comment]
@simoneldevig my chrome extension works properly

Since my toggl times are listed in the add on, I’m sure the api is right and is connected. Everything works fine until I hit the button: LOG WORK

Then a red bar appears with. Error: Request failed with status 403

Tried in private mode, tried to reinstall firefox completely. Tried on different wireless connections...

**Comment by simoneldevig** [comment]
@herrpina alright. I will try to test in the weekend. Maybe Firefox added some security measures which breaks the JIRA integration

**Comment by herrpina** [comment]
@simoneldevig thanks, I tried it on another mac with firefox and it doesn’t work neither. On another mac it used to work but after updating to latest version, it doesn’t work anymore.

**Comment by simoneldevig** [comment]
@herrpina I managed to fix the issue which was caused by a bug in JIRA with the new User-Agent String (https://community.atlassian.com/t5/Jira-questions/Jira-7-rest-api-XSRF-check-failed-for-post-issue-with/qaq-p/488706)

Published 1.4.1 to Firefox which should be out in a couple of days.

**Comment by herrpina** [comment]
thanks a lot for the fast work. You made many people happy!

**Comment by herrpina** [comment]
Hi Simon,
just another question: is it possible that it fetches the Jira ticket number from the project name as well as the description? At this moment I have to choose which one and it should be better that it fetches from the description and the project name...

**Comment by simoneldevig** [comment]
@herrpina that would have to be a new setting, but it's not something that's on the roadmap for now, but you're welcome to create a pull-request with feature :-)

**Comment by herrpina** [comment]
Hi Simon,

Something has changed I think, since today our team can't sync their tasks anymore. I get an error 404. Other similar extensions aren't working neither. Problem occurs in chrome and Firefox...

**Comment by simoneldevig** [comment]
@herrpina can you send me the errors that shows up in the developer console?

Open the extension, right click on the window and choose inspect. It should show an error in the console tab.

I have no issues syncing to JIRA Cloud ATM

**Comment by herrpina** [comment]
hi simon,

I think it was a problem on our side, the issue has been resolved :)
