### ISSUE TITLE
Feat: Remember selected dates between each openings

### ISSUE THREAD

**Issue by dogawaf** [simoneldevig/jira-toggl#20]
Hi

The calendar should remember the selected dates between each openings

**Comment by simoneldevig** [comment]
Hi @dogawaf 

Interesting suggestion. It would have to be persistent in the browser storage, but the question is for how long? 

The current session or maybe a day?

Just like #21 it's not something I currently have time for, but you're welcome to create a PR for the feature :-)

**Comment by simoneldevig** [comment]
@dogawaf this has been implemented in V1.6.0 :-)
