### ISSUE TITLE
Feat: Add an option to set the day of the week

### ISSUE THREAD

**Issue by dogawaf** [simoneldevig/jira-toggl#21]
Hi

The first day of the week should be defined in options:
- Week starts on monday
- Week starts on sunday

**Comment by simoneldevig** [comment]
Hey @dogawaf 

Thx for the suggestion. I currently don't have time to implement this, but you're welcome to create pull request and then I'll have a look at it :-)

**Comment by simoneldevig** [comment]
@dogawaf this has been implemented in V1.6.0 :-)
