### ISSUE TITLE
Timeentries are not being marked as Logged

### ISSUE THREAD

**Issue by michael-schmetter** [simoneldevig/jira-toggl#31]
Hi,
I'm currently trying to get the Browser-Extensions to work properly, and so far it works good.
The only issue I found is, that already synched worklog entries are not marked as logged:
Syncing:
![image](https://user-images.githubusercontent.com/24694463/135835362-39683058-4df8-47b4-8c87-86aafe1c58e6.png)
Synced in Jira:
![image](https://user-images.githubusercontent.com/24694463/135835472-1a961285-a583-4ae9-a92a-9a3ad69a2f32.png)
Not marked as logged:
![image](https://user-images.githubusercontent.com/24694463/135835702-081039a0-629f-4c28-a28f-7a9bf31d2122.png)

Is someone else have that issue?

**Comment by simoneldevig** [comment]
@michael-schmetter it uses the Jira email to figure out if the entry is logged or not. Have you filled out the Jira email and double checked that it's same that is used in Jira? :-)

**Comment by michael-schmetter** [comment]
@simoneldevig Thank you very much!
Indeed that was the issue, I had entered there my Jira logon which is not the same as the email.
