### ISSUE TITLE
Request to Toggl api are failing

### ISSUE THREAD

**Issue by dogawaf** [simoneldevig/jira-toggl#35]
Toggl has changed its product names since a while.
https://toggl.com/blog/api-documentation-change

Now, the Toggl track api is located at api.track.toggl.com and www.toggl.com/api is not responding anymore.
This extension needs some adaptation to the new urls: https://github.com/toggl/toggl_api_docs

**Comment by ovchingus** [comment]
Yeah, extension don't work now.

**Comment by simoneldevig** [comment]
Fixed in #36 and pushed version 1.6.4 to Google Web Store who hopefully will release it soon.
