### ISSUE TITLE
Migrate to Toggl API v9 before April 1 2023, when v8 will be disabled

### ISSUE THREAD

**Issue by rogatty** [simoneldevig/jira-toggl#54]
API v8 which is being used by this extension is deprecated since Oct 1 2022: [developers.track.toggl.com/changes/2022/10/01/api-v8-deprecation](https://developers.track.toggl.com/changes/2022/10/01/api-v8-deprecation)

During March 2023 there will be brownouts:

>During brownout periods, endpoints will be temporarily disabled and then re-enabled after a few hours. The goal is to help API clients to notice the scheduled unavailability and plan their migration accordingly.

On April 1 2023 the v8 will be disabled and the extension will stop working.

Here is the migration guide: [developers.track.toggl.com/docs/additional/v8_migration_guide](https://developers.track.toggl.com/docs/additional/v8_migration_guide)

**Comment by simoneldevig** [comment]
The 1.7.0 release uses v9. 

It's uploaded to the Chrome store and pending approval
